== Summary
(( This OGC Engineering Report (ER) documents the results of the CDB Vector Data in GeoPackage Interoperability Experiment (IE). The participants in this IE tested the encoding of vector data into one or more GeoPackage(s) and storing the result in a CDB data store. GeoPackage Version 1.2 and CDB Version 1.1 and related Best Practices were the standards baseline used for this experiment. The IE builds on the work described in the OGC "CDB, Leveraging GeoPackage" Discussion Paper. ))

(( A primary objective of this IE was to agree and document possible change requests and/or best practices for storing vector data in a CDB data other than ShapeFiles. These suggested changes requests and/or best/practices would be used as the basis for SDB SWG discusions related to possible revisions to the CDB standard. ))

(( Once the IE activity is completed, Insert key findings here. ))

=== Requirements & Research Motivation
(( In the commercial modelling and simulation industry, geospatial data content and use is exploding at a rate that is outpacing the innovation and utilization of the traditional M&S industry. The M&S and geospatial-intelligence (GEOINT) industries are on a path of convergence. Within the OGC, there are two geospatial standards that best enable the unification of the M&S and GEOINT industries: OGC CDB and GeoPackage. OGC CDB and GeoPackage are both standards increasingly used in M&S and GEOINT industry, but they both contain weaknesses and strengths when it comes to the combined needs of both industries. ))

=== Prior-After Comparison
(( This IE is based on preliminary work conducted under funding by the U.S. Army Geospatial Center (AGC), the results of which have been publicly released as OGC Document Number 18-077:  OGC CDB and GeoPackage Discussion Paper   (https://portal.opengeospatial.org/files/?artifact_id=80537&version=1). The Discussion Paper documents the results of research, design, and prototype efforts to present the OGC with an approach to creating “GeoCDB” — a technology mashing of GeoPackage and OGC CDB — as a deterministic repository of easily read data geospatial datasets suitable for storage, runtime access, and dissemination for live, virtual, constructive, gaming, and mission command (MC) systems. ))

=== Recommendations for Future Work
(( This section should answer the question: What does this ER mean for the Working Group and OGC in general? What aspects shall be addressed next? In any specific order? What actions are necessary? ))

(( This is a write up for why this ER should be important to the working group and OGC. This paragraph provides recommendations on how to further proceed with the achievements documented in this ER. ))

===	Document contributor contact points

All questions regarding this document should be directed to the editor or the contributors:

*Contacts*
[width="80%",options="header",caption=""]
|====================
|Role| Name |Organization
|((editor)) | (( TBD )) | (( organization ))|
|((Initiator)) | (( David Graham )) | (( CAE ))|
|((Initiator)) | (( Kevin Bentley )) | (( Cognitics ))|
|((editor)) | (( TBD )) | (( organization ))|
|====================


// *****************************************************************************
// Editors please do not change the Foreword.
// *****************************************************************************
=== Foreword

Attention is drawn to the possibility that some of the elements of this document may be the subject of patent rights. The Open Geospatial Consortium shall not be held responsible for identifying any or all such patent rights.

Recipients of this document are requested to submit, with their comments, notification of any relevant patent claims or other intellectual property rights of which they may be aware that might be infringed by any implementation of the standard set forth in this document, and to provide supporting documentation.
