== Terms and definitions

For the purposes of this report, the definitions specified in Clause 4 of the OWS Common Implementation Standard https://portal.opengeospatial.org/files/?artifact_id=38867&version=2[OGC 06-121r9] shall apply. In addition, the following terms and definitions apply.

* term name

 text of the definition

* term name|synonym

 text of the definition


===	Abbreviated terms

.NOTE: The abbreviated terms clause gives a list of the abbreviated terms and the symbols necessary for understanding this document. All symbols should be listed in alphabetical order. Some more frequently used abbreviated terms are provided below as examples.

    CRS  Coordinate Reference System
    DDIL Denied, Degraded, Intermittent, or Limited
    GPKG GeoPackage
    KML  Keyhole Markup Language
    OGC  Open Geospatial Consortium
    OWS  OGC Web Services
    SRS  Spatial Reference System
    SWG  Standards Working Group
    WFS  Web Feature Service
    WMS  Web Map Service
    WMTS Web Map Tile Service
