[[Overview]]
== Overview

=== IE Overview
The current approved OGC CDB 1.1 Standard provides a Best Practices document describing the encoding of vector data using Esri Shapefiles.   All previous versions of CDB (including OGC CDB Standard 1.0 and the Industry-maintained CDB Specification 3.2 and prior) have only described vector data encoding in Shapefiles.  All known CDB content and repositories that include vector data are encoded using Shapefiles.  As a result, there have been numerous requests to test and document how other vector envodings could be stored in a CDB data store.  This requirement is captured in OGC Change Request http://ogc.standardstracker.org/show_request.cgi?id=545[545]. Another identified issue is that every use of Shapefiles creates four physical files on storage which has performance implications.

The goal of this IE will be achieved by replicating the experimentation conducted in the Discussion Paper by IE participants who are CDB content creators, maintainers of CDB repositories, implementers of CDB datasets in run-time and non-run-time CDB use cases, or new CDB 1.1 users who are evaluating CDB implementations.

These IE participants will produce an OGC Engineering Report that discusses whether the recommended alternate encoding of CDB vector data as a GeoPackage is fit for use and submission to the OGC for consideration as an approved change to the OGC CDB 1.1 Standard and/or Best Practices.

=== Engineering Report Section Overviews. 

(( Section 5 introduces the background and requirements for adding GeoPackages as a storage format in a CDB data store. It describes the situation prior to the Interoperability Experiment and discusses the requirements defined by the CDB user base. ))

(( Section 6 discusses the experiments in detail. The concept of operation also provides recommendations on preferred strategies. ))

(( Section 7 discusses the results of the various experiments performed as part of this initiative. A clear mapping of requirements for proposed GeoPackages in a CDB datastore candidate standard/best practice is provided. ))

(( Section 8 provides a summary of the main findings and discusses proposed change requests. ))

(( Annex A provides detailed performance information.))
