[[CONOPSClause]]
== IE Overview and Concept of Operations
=== IE Overview
The current approved OGC CDB 1.1 Standard provides a Best Practices document describing the encoding of vector data using Esri Shapefiles.   All previous versions of CDB (including OGC CDB Standard 1.0 and the Industry-maintained CDB Specification 3.2 and prior) have only described vector data encoding in Shapefiles.  All known CDB content and repositories that include vector data are encoded using Shapefiles.  As a result, there have been numerous requests to test and document how other vector envodings could be stored in a CDB data store.  This requirement is captured in OGC Change Request http://ogc.standardstracker.org/show_request.cgi?id=545[545]. Another identified issue is that every use of Shapefiles creates four physical files on storage which has performance implications.

The goal of this IE will be achieved by replicating the experimentation conducted in the Discussion Paper by IE participants who are CDB content creators, maintainers of CDB repositories, implementers of CDB datasets in run-time and non-run-time CDB use cases, or new CDB 1.1 users who are evaluating CDB implementations.

These IE participants will produce an OGC Engineering Report that discusses whether the recommended alternate encoding of CDB vector data as a GeoPackage is fit for use and submission to the OGC for consideration as an approved change to the OGC CDB 1.1 Standard and/or Best Practices.

=== IE Experiments: Overview
==== Experiment #1: Data Preparation and General Workflow

The methodology involves:

   * Acquisition of sample dataset(s) provided for the IE.
   * Use of provided open-source software to modify each sample dataset according to the three technical alternatives.  
   * Consensus and provision of baseline (unmodified) and three alternative encoding datasets.
   * Evaluate process and provide feedback on conversions resulting from Experiment #1.

==== Experiment #2: 1.	Replace each Shapefile with a GeoPackage

The methodology involves:

   * Modifying implementation software according to Alternative #1.
   * Replace each Shapefile, consolidating the three geometry files with a single GeoPackage.
   * Evaluate and compare performance using the baseline CDB datasets and the Alternative #1 datasets.
   * Evaluate analysis and results from Experiment #2  for performance, backwards-compatibility and risks to interoperability.

==== Experiment #3: Store each CDB LOD as a layer in GeoPackage 

The methodology involves: 

   * Modifying implementation software according to Alternative #2.
   * Store each CDB LOD as a layer in GeoPackage
   * Evaluate and compare performance using the baseline CDB datasets and the Alternative #2 datasets.
   * Evaluate analysis and results from Experiment #3 for performance, backwards-compatibility and risks to interoperability.

==== Experiment #4: Store all the Vector Data of a Geocell in one GeoPackage 

The methodology involves:

   * Modifying implementation software according to Alternative #3.
   * Store each Geocell of Vector Data as a layer in GeoPackage (extends Alternative #3 to have a single GeoPackage per Geocell of CDB, with all LODs and all CDB feature layers).
   * Evaluate and compare performance using the baseline CDB datasets and the Alternative #3 datasets.
   * Evaluate analysis and results from Experiment #4 for performance, backwards-compatibility and risks to interoperability.

=== Who is doing what

==== Hexagon/Luciad

For our involvement as a participant in the current GeoPackage conversion IE we are at this point planning to complete all listed experiments (1 - 4).

Additionally, we are currently modifying our existing CDB client software to produce the converted vector data in the GeoPackage format and are implementing Option 1d of the conversion strategies.

We will be focused primarily on the client visualization performance for our contribution to the ER. As discussed on last week's call we will also provide some file system metrics after the data conversion. If time permits we will perform the conversions and experiments for all three datasets.
