[[references]]
== References

The following documents are referenced in this document. For dated references, subsequent amendments to, or revisions of, any of these publications do not apply. For undated references, the latest edition of the normative document referred to applies.


* OGC 06-121r9, OGC® Web Services Common Standard

.NOTE: 	This OWS Common Standard contains a list of normative references that are also applicable to this Implementation Standard.

* ISO xyz (all parts), General title of the series of parts.

(( The reference(s) clause gives a list of the documents to which reference is made in the document in such a way as to make them indispensable for the application of the document. ))

(( The list shall not include the following: ))

*	documents that are not publicly available;
*	documents which have merely served as references in the preparation of this document. Such documents may be listed in a bibliography.

(( For dated references, each shall be given with its year of publication, or, in the case of enquiry or final drafts, with a dash together with a footnote «To be published.», and full title. Subsequent amendments to, or revisions of, dated references will need to be incorporated by amendment of the document referring to them. References to specific divisions or subdivisions, tables and figures of another document shall always be dated. ))

(( Undated references may be made only to a complete document or a part thereof, and only if it is accepted that it will be possible to use all future changes of the document referred to for the purposes of the referring standard. Undated references shall be understood to include all amendments to and revisions of the quoted publication. The year of publication or dash shall not be given for undated references. When an undated reference is to all parts of a document, the publication number shall be followed by the indication «(all parts)» and the general title of the series of parts (i.e. the introductory and main elements). ))



